### PR TITLE
Revamp (WIP)

### PR DESCRIPTION
**Pull request by krainboltgreene**
I went ahead and rewrote the entire app from scratch. It's fully working and hosted on http://nolavation-de-production.herokuapp.com/

Here are some noticeable differences:
- Splash page now has a working timeline.
- Entries json is now correctly pumped out according to timeline expectancy
- Assets are hosted on S3, with a Cloundfront gateway
- Signing in via Facebook, Twitter, or Linkedin now works for sure.
- The import python script works, and is tested (see splash page)
- The entry form is open for people to submit data (after having been authenticated)
- Entries now have tags and that whole shebang works
- Full setup guide in the README
- We're using Unicorn, which'll handle more concurrent load than webbrick

Some minor problems:
- A bit of the CSS is wonky, but still within MVP-okay levels.
- Timeline.js is a terrible library, but great design/concept. Further movement may be tricky.
- Until Timeline.js is replaced or fixed or refactored adding new crap isn't easy (for me)
- We're using Difference Engineers, LLC's AWS, Twitter, Linkedin, and Facebook Key/Secrets

### CODE REVIEW

**Comment by krainboltgreene** [comment]
Looking into a problem with the Facebook login, I think it's a setting issue on the Facebook App Config.

**Comment by ericnormand** [comment]
Hey Kurtis,

Very impressive work! I'll pull it and try it out.

If I don't talk to you before then, see you tomorrow! I should buy you a
beer.

Eric

On Mon, Jul 16, 2012 at 5:22 PM, Kurtis Rainbolt-Greene <
reply@reply.github.com

**Comment by ericnormand** [comment]
Hey Kurtis!

I'm looking at the heroku app but I can't seem to log in. Clicking login
just brings up a dropdown.

Eric

On Mon, Jul 16, 2012 at 5:22 PM, Kurtis Rainbolt-Greene <
reply@reply.github.com

**Comment by mshwery** [comment]
I'm seeing an issue with the Gemfile.

**Comment by krainboltgreene** [comment]
@mshwery What's wrong with the Gemfile?

**Comment by krainboltgreene** [comment]
@ericnormand Yeah, the best way to log in right now is via /sesssions/new. I'm trying to figure out a problem with the Facebook callback though.

**Comment by krainboltgreene** [comment]
@mshwery When you get the chance, comment on where the gemfile problem is.

**Comment by krainboltgreene** [comment]
Bah, stupid typo. All fixed. Reopening pull request in another PR. I accidentally pushed revamp to master. Did a hard reset, force pushed hard reset, but Github is still confused.

**Comment by mshwery** [comment]
Sorry Kurtis, I had no intention of closing the PR when I commented.

**Pull request merged**
