### PR TITLE
Refactor of application

### PR DESCRIPTION
**Pull request by krainboltgreene**
Same as old. Github accidentally marked it as accepted and merged. Here's the previous notes:

I went ahead and rewrote the entire app from scratch. It's fully working and hosted on http://nolavation-de-production.herokuapp.com/

Here are some noticeable differences:
- Splash page now has a working timeline.
- Entries json is now correctly pumped out according to timeline expectancy
- Assets are hosted on S3, with a Cloundfront gateway
- Signing in via Facebook, Twitter, or Linkedin now works for sure.
- The import python script works, and is tested (see splash page)
- The entry form is open for people to submit data (after having been authenticated)
- Entries now have tags and that whole shebang works
- Full setup guide in the README
- We're using Unicorn, which'll handle more concurrent load than webbrick

Some minor problems:
- A bit of the CSS is wonky, but still within MVP-okay levels.
- Timeline.js is a terrible library, but great design/concept. Further movement may be tricky.
- Until Timeline.js is replaced or fixed or refactored adding new crap isn't easy (for me)
- We're using Difference Engineers, LLC's AWS, Twitter, Linkedin, and Facebook Key/Secrets

### CODE REVIEW

**Comment by krainboltgreene** [comment]
In addition I've also now added:
- Search, both title, body, and tags
- Markdown formatting for the entry bodies.

**Comment by krainboltgreene** [comment]
Forgot to add `oauth_token` and `oauth_expires_at` fields for the oauth login, but it looks like Twitter is working.

**Comment by krainboltgreene** [comment]
Ran into a new issue, documenting for science and sleep:

```
2012-07-17T09:32:51+00:00 app[web.1]: NoMethodError (undefined method `sorcery_config' for #<Account:0x00000003ba4e08>):
2012-07-17T09:32:51+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.6/lib/active_model/attribute_methods.rb:407:in `method_missing'
2012-07-17T09:32:51+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/attribute_methods.rb:149:in `method_missing'
2012-07-17T09:32:51+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bundler/gems/sorcery-71a978fcd7d7/lib/sorcery/controller/submodules/
```

**Comment by mshwery** [comment]
We need some validation on the form.

We should also only allow adding entries if you are a signed in user (so we can grab your username and attribute it creating/updating the story).

I'll be available to help work on this at Hack Night.

**Comment by krainboltgreene** [comment]
@mshwery I can get some easy validation up, but let me know how the markup should look on the errors. We can also use SimpleForm to handle all that jazz.

**Comment by mustmodify** [comment]
Per Barrett, I am reverting master to the way it was at the end of Sunday's festivities. I assume he will want to pull this branch in, so let's not remove it. He wants to have a conversation about it at Hack Night tonight.

**Pull request merged**
